name: cefi-cookbook-dev
channels:
  - conda-forge
dependencies:
  - python=3.10
  - dask
  - netcdf4
  - erddapy=1.2.1
  - scipy
  - xarray
  - matplotlib
  - folium
  - bokeh
  - plotly
  - jupyter-book
  - jupytext
  - ghp-import
  - jupyter-cache
  - cf_xarray
  - cartopy
  - zarr<3
  - fsspec
  - gcsfs
  - s3fs
  - r-irkernel
  - r-rerddap
  - r-ncdf4
  - r-maps
  - r-reticulate
  - r-dplyr
  - r-ggplot2
